# This workflow will run our tests, generate an lcov code coverage file,
# and send that coverage to Coveralls 

name: Code Coverage

on: workflow_call

jobs:
  call_code_coverage:
    uses: yext/slapshot-reusable-workflows/.github/workflows/coverage.yml@v1
    with:
      comparison_branch: master
    secrets:
      caller_github_token: ${{ secrets.GITHUB_TOKEN }}
