name: Sync Main to Storybook Site Branch & Test Site Branch

on:
  push:
    branches:
      - master
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
