name: Sync Main to Storybook Site Branch & Test Site Branch

on:
  push:
    branches:
      - master
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mtanzi/action-automerge@v1
        with:
          source: "${{ github.event.repository.default_branch }}"
          target: "test"
          github_token: ${{ secrets.GITHUB_TOKEN }}
