name: Check and Update Repo's documenation

on: pull_request

jobs:
  call_update_docs:
    uses: yext/slapshot-reusable-workflows/.github/workflows/update_docs.yml@dev/update-third-party-notices-check
    with:
      build_script: npm run build-ci
    secrets:
      REPO_SCOPED_TOKEN: ${{ secrets.TEST_REPO_SCOPED_WITHOUT_ORG }}
