name: Check and Update Repo's documenation

on: workflow_call

jobs:
  call_update_docs:
    uses: yext/slapshot-reusable-workflows/.github/workflows/update_docs.yml@dev/test-output-env-file
    with:
      build_script: npm run build-ci
